name: dynamic-env

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/dynamic-env.yaml"

env:
  CI: false
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        name: checkout

      - name: Init
        shell: bash
        run: |
          echo ::set-env name=BRANCH::"$(git rev-parse --abbrev-ref HEAD)" && echo $BRANCH
          echo ::set-env name=REPOSITORY_NAME::$(echo "database-versioning")
          echo ::set-env name=DEPLOYMENT::$(echo "database-versioning")
      - name: Find recent changes in changelog and print this console
        shell: bash
        run: |
          cd dynamic-env-keys
          source dynamic-env-config.env
          source $(echo "./"$SOURCE"/config.env")
          source $(echo "./"$DESTINATION"/config.env")

          echo $SOURCE
          echo $DESTINATION
          
          eval SOURCE_ENV1=\$$SOURCE"_ENV1"
          eval DESTINATION_ENV1=\$$DESTINATION"_ENV1"
          echo $SOURCE_ENV1
          echo $DESTINATION_ENV1


